### PR TITLE
Edit the Website and Edit the format of the code...

### PR DESCRIPTION
**Pull request by alisamadiii**
### 1. Change the format of Code:
```diff
- export default function Home() {}
+ const Home = ()  => {}
+ export default Home
```
### 2. Added 3 components:
   - FunFacts1.component.jsx
   - FunFacts2.component.jsx
   - SharkInfo.component.jsx
 
**Before**
image
**After**
image

### CODE REVIEW

**Review by zelfroster — APPROVED** [review]
Amazing and Awesome work Ali
Thank you so much ❤️

**Comment by zelfroster** [comment]
Is everything finalized now??
Should I merge this PR now?

**Comment by alisamadiii** [comment]
Yes, You can merge it. @zelfroster

**Comment by alisamadiii** [comment]
> Amazing and Awesome work Ali Thank you so much ❤️

Thanks Sumit

**Pull request merged**
