### PR TITLE
I've added animation

### PR DESCRIPTION
**Pull request by alisamadiii**
Issue #34 
No screenshots because I could not do it, I have to show the project by video.
NP, You guys check it and let me know it is working or not.

### CODE REVIEW

**Comment by alisamadiii** [comment]
It is working Fine Thanks God...

**Comment by zelfroster** [comment]
Hey Ali, Did you use npm or yarn?

**Comment by alisamadiii** [comment]
@zelfroster I used NPM

**Comment by alisamadiii** [comment]
Will it make a problem @zelfroster ?

**Comment by zelfroster** [comment]
Looks like we should have mentioned that we used yarn for our project. 😅 
It might sound terrible but could you use yarn again... Because I think It is not advised to mix package managers.

**Comment by zelfroster** [comment]
Btw changes are nice.. animations look nice 💯

**Comment by alisamadiii** [comment]
I don't have yarn RN but will do it NP.

**Comment by zelfroster** [comment]
Thank you so much Ali...
Also you can install yarn by running this command since you already have npm
- Permanently
```
npm install --global yarn
```
**or**
- Only for this project
``` 
npm install yarn
```

**Comment by alisamadiii** [comment]
I just used
```console
$ yarn install gsap
```
and copy all the code in yarn.lock and paste here.

**Comment by alisamadiii** [comment]
is it good RN? @zelfroster

**Comment by zelfroster** [comment]
> is it good RN? @zelfroster

Yes and do one more thing.. remove the ```package-json.lock``` file

**Comment by alisamadiii** [comment]
Done @zelfroster

**Comment by zelfroster** [comment]
Awesome work Ali 💯

**Review by zelfroster — APPROVED** [review]
Great Job Ali 💯 
Thanks for contributing and giving your valuable time ❤️

**Comment by alisamadiii** [comment]
Thank You for letting me to contribute on this project with you.

**Pull request merged**
